@startuml

[*] --> S_INIT
S_INIT --> S_ACQUISITION : E_START / A_INIT
S_ACQUISITION <-right- S_FORGET :  E_CONTINUER / A_NOP
S_ACQUISITION -down-> S_DEPLACEMENT : E_INPUT_HAUT / A_DEPLACER_HAUT \n E_INPUT_DROITE / A_DEPLACER_DROITE \n E_INPUT_GAUCHE / A_DEPLACER_GAUCHE\n  E_INPUT_BAS / A_DEPLACER_BAS
S_ACQUISITION -down-> S_FIN : E_INPUT_QUITTER / A_TERMINER
S_ACQUISITION --> S_ACQUISITION : E_CONTINUER / A_AFFICHER

S_DEPLACEMENT --> S_PIRATE : E_DEPLACEMENT_FINI / A_MOUVEMENT_PIRATE
S_DEPLACEMENT --> S_FIN : E_INPUT_QUITTER / A_TERMINER

S_PIRATE --> S_VERIFICATION : E_PIRATE_FINI / A_VERIFIER
S_PIRATE --> S_FIN : E_INPUT_QUITTER / A_TERMINER

S_VERIFICATION --> S_FIN : E_VICTOIRE / A_TERMINER \n E_DEFAITE / A_TERMINER \n E_INPUT_QUITTER / A_TERMINER
S_VERIFICATION --> S_ACQUISITION : E_CONTINUER / A_AFFICHER

S_INIT ----> S_FIN : E_INPUT_QUITTER / A_TERMINER
S_FIN --> [*]